// @ts-check
import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";
import { readFileSync } from "node:fs";

// Old WordPress URLs -> current ones. GitHub Pages has no server-side redirects, so Astro emits a
// meta-refresh stub page for each. src/data/redirects.csv is regenerated by wxr_to_astro.py.
const redirects = Object.fromEntries(
  readFileSync("src/data/redirects.csv", "utf8")
    .split("\n")
    .slice(1)
    .filter((l) => l.includes(","))
    .map((l) => l.split(",").map((s) => s.trim()))
    .filter(([from, to]) => from && to && from !== to),
);

export default defineConfig({
  site: "https://humancompatible.ai",
  // WordPress URLs all ended in "/"; keep that so nothing external breaks.
  trailingSlash: "always",
  build: { format: "directory" },
  integrations: [sitemap()],
  redirects,
  // Content was converted from WordPress HTML; typography (curly quotes, dashes) is already applied by the
  // extractor, and WordPress never autolinked bare URLs/emails — so keep Markdown rendering literal.
  markdown: { gfm: false, smartypants: false },
});
